openapi: 3.0.1
info:
  title: Web5 Plugin
  description: A plugin that assist users to build web5 applications using the web5 sdk.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /help/setup:
    get:
      operationId: helpSetup
      summary: show how to get setup with web5 in javascript or typescript
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/instructionResponse'

  /help/did:
    get:
      operationId: helpDid
      summary: how to create a decentralized identifier (DID) programmatically
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/instructionResponse'                

  /help/store:
    get:
      operationId: helpStore
      summary: how to store data in web5
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/instructionResponse'   

  /help/write-send:
    get:
      operationId: writeSend
      summary: Write to a local DWN and send to a remote (Alice to Bob)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/instructionResponse'      
  /help/query:
    get:
      operationId: helpQuery
      summary: how to query data via a records id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/instructionResponse'                                
  /help/query-full:
    get:
      operationId: helpQueryFull
      summary: how to query data from local or remote DWNs via protocol
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/instructionResponse'
  /help/protocol:
    get:
      operationId: helpProtocol
      summary: What a protocol in web5 is with an example and how to set it up/install it
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/instructionResponse'                
  /help/html-import:
    get:
      operationId: helpHtml
      summary: How to setup and use web5 in a html page script tag
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/instructionResponse'                     
  

components:
  schemas:
    instructionResponse:
      type: object
      properties:
        code:
          type: string
          description: a sample piece of code
        explanation:
          type: string  
          description: what the sample code does.